# Generated by Django 5.0.3 on 2024-03-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste_mat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_name', models.CharField(max_length=50)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewaste.category')),
            ],
        ),
        migrations.CreateModel(
            name='Total_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_use', models.CharField(max_length=30)),
                ('waste_cost', models.IntegerField()),
                ('waste_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewaste.waste_mat')),
            ],
        ),
    ]
