# Generated by Django 5.0.3 on 2024-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0004_alter_category_cat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_cat',
            name='waste_use',
            field=models.CharField(max_length=1000),
        ),
    ]
