# Generated by Django 5.0.3 on 2024-04-01 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0006_total_cat_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_cat',
            name='cat_name',
            field=models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.CASCADE, to='ewaste.category'),
        ),
        migrations.AlterField(
            model_name='total_cat',
            name='waste_cost',
            field=models.IntegerField(db_column='waste_cost'),
        ),
        migrations.AlterField(
            model_name='total_cat',
            name='waste_name',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='ewaste.waste_mat'),
        ),
        migrations.AlterField(
            model_name='total_cat',
            name='waste_use',
            field=models.CharField(db_column='waste_name', max_length=1000),
        ),
    ]
